# Documentation: http//docs.travis-ci.com/user/language/julia/
language: julia
os:
    - linux
    - osx
julia:
    - 0.7
    - 1.0
    - nightly
git:
    depth: 999999
matrix:
    allow_failures:
        - julia: nightly
notifications:
    email: false
after_success:
    - julia -e 'cd(Pkg.dir("Node2Vec")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
env:
    - CODECOV_TOKEN="d351530e-3dc7-45d3-8851-03ea0da9e933"
